### ISSUE TITLE
Cannot load internationalized FXML files

### ISSUE THREAD

**Issue by xb** [byteit101/JRubyFX-FXMLLoader#2]
Apparently, JRubyFX-FXMLLoader is currently (the current GIT repository head) not able to load any FXML file which has internationalized names.
## How to reproduce
1. Create an FXML file with the JavaFX Scene Builder (1.1 preview)
2. Create a button.
3. Edit the text of the button: Replace it with an internationalized string as explained here: http://docs.oracle.com/javafx/scenebuilder/1/user_guide/i18n-support.htm
4. Attempt to load the FXML file in a JRubyFX project as normal (that is, using the "fxml" method).
## Expected result

The application is loaded.
## Actual result

An exception is raised:

```
org.jruby.exceptions.RaiseException: (LoadException) No resources specified.
        at RUBY.resolvePrefixedValue(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/elts.rb:363)
        at RUBY.processValue3(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/elts.rb:306)
        at RUBY.processPropertyAttribute(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/elts.rb:261)
        at RUBY.processInstancePropertyAttributes(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/elts.rb:163)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1617)
        at RUBY.processInstancePropertyAttributes(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/elts.rb:162)
        at RUBY.processEndElement(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/value_elts.rb:86)
        at RUBY.processEndElement(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/jrubyfx-fxmlloader.rb:588)
        at RUBY.load(/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/jrubyfx-fxmlloader.rb:367)
        at RUBY.load_fxml_only(/foobar/gems/jrubyfx-1.0.0-java/lib/jrubyfx/controller.rb:258)
        at RUBY.fxml(/foobar/gems/jrubyfx-1.0.0-java/lib/jrubyfx/core_ext/stage.rb:80)
```
## Further comments

Trying to work around this problem by leveraging the fx:include feature as follows

```
    <fx:include source="foobar.fxml">
```

also fails:

```
#<NoMethodError: undefined method `resources' for #<FxmlLoader:0x765a4f09>>
/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/fxmlloader/real_elts.rb:204:in `initialize'
/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/jrubyfx-fxmlloader.rb:547:in `createElement'
/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/jrubyfx-fxmlloader.rb:456:in `processStartElement'
/foobar/gems/jrubyfx-fxmlloader-0.3-java/lib/jrubyfx-fxmlloader.rb:364:in `load'
/foobar/gems/jrubyfx-1.0.0-java/lib/jrubyfx/controller.rb:258:in `load_fxml_only'
/foobar/gems/jrubyfx-1.0.0-java/lib/jrubyfx/core_ext/stage.rb:80:in `fxml'
```

**Comment by byteit101** [comment]
JRubyFX 2.0 has been release, rendering this gem obsolete. If your issue still applies to JRubyFX 2.0, please reopen this issue on the JRubyFX issue tracker.
